import:
  - ~/.config/alacritty/themes/themes/argonaut.yaml

window:
  opacity: 0.95
  padding:
    x: 3
    y: 3
  dynamic_padding: true
  resize_increments: true
  option_as_alt: OnlyLeft
font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  size: 14.0
key_bindings:
  - { key: S, mods: Command, chars: "\e:w\n" }
