import:
  - ~/.config/alacritty/themes/themes/dracula.yaml

env:
  TERM: alacritty-direct

window:
  opacity: 1
  padding:
    x: 3
    y: 3
  dynamic_padding: true
  resize_increments: true
  option_as_alt: OnlyLeft
font:
  normal:
    family: FiraCode Nerd Font
    style: Retina
  italic:
    family: OperatorMono Nerd Font
    style: ExtraLight Italic
  size: 14.0
key_bindings:
  - { key: S, mods: Command, chars: "\e:w\n" }
  - { key: Tab, mods: Control, chars: "\x1b[27;5;9~" }
  - { key: Tab, mods: Control|Shift, chars: "\x1b[27;6;9~" }
