#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         5
bspc config window_gap         20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Chromium" desktop='^2'
bspc rule -a "mpv" state=floating
bspc rule -a "Show-splash-gtk" desktop='^7' state=floating
bspc rule -a "Bitwig Studio" desktop='^7'
bspc rule -a "Spotify" desktop='^5'


xsetroot -cursor_name left_ptr &


